---
models:
  - allcnn-96-144
  - wr-4-8
  - fc-1024-512-256-128
  - convmixer-1536-20
  - vit-4-512
bs: 
  - 200
  - 400
  - 1000
bn: # training convmixer without bn is almost impossible, vit uses layernorm instead of bn
  - False
  - True
aug:
  - False
  - True
wd:
  - 0.0
  - 0.1
opts:
  - sgd
  - sgdn
  - adam
corner:
  - normal
  - uniform 
  - subsample-200 
  - subsample-2000