---
optimizer: AdamW
bs: 500
batch_seed: -1
epochs: 25
autocast: False
opt_args:
  weight_decay: 0.005
  lr: 0.05
scheduler: "cosine_with_warmup"
sched_args:
  cycle_mult: 1
  warmup_steps: 10
  gamma: 0.5