---
optimizer: SGD 
bs: 200
epochs: 200
opt_args:
  weight_decay: 0.0
  lr: 0.05
  momentum: 0.9
  nesterov: True
scheduler: cosine_with_warmup
sched_args:
  cycle_mult: 1
  warmup_steps: 10
  gamma: 0.1