---
corner: "uniform"
init_opt:
  optimizer: AdamW
  bs: 200
  batch_seed: -1
  epochs: 200
  autocast: False
  opt_args:
    weight_decay: 0.0001
    lr: 0.05
  scheduler: cosine_with_warmup
  sched_args:
    cycle_mult: 1
    warmup_steps: 10
    gamma: 0.1
  